# full config options are documented at
# https://github.com/martinvonz/jj/blob/main/docs/config.md

[user]
email = "dustypomerleau@users.noreply.github.com"
name = "Dusty Pomerleau"

# available options are listed at
# https://github.com/martinvonz/jj/blob/main/cli/src/config/colors.toml
[colors]
"commit_id" = "bright white"
"committer" = "bright black"
"email" = "bright black"
"empty" = "red"
"empty description placeholder" = "green"
"git_head" = "cyan"
"git_refs" = "cyan"
"operation current_operation id" = "yellow"
"operation current_operation time" = "bright white"
"operation current_operation user" = "bright black"
"operation id" = "magenta"
"operation time" = "blue"
"operation user" = "bright black"
"remote_bookmarks" = "green"
"tags" = "cyan"
"timestamp" = "bright black"
"working_copy change_id" = "cyan"
"working_copy commit_id" = "bright white"
"working_copy committer" = "yellow"
"working_copy description placeholder" = "bright green"
"working_copy email" = "yellow"
"working_copy empty" = "red"
"working_copy timestamp" = "blue"

[diff]
format = "git"

[git]
auto-local-bookmark = false
push-bookmark-prefix = ""

[template-aliases]
"format_short_id(id)" = "id.shortest()"

[ui]
editor = "nvim"
merge-editor = "vscode"
pager = "delta"
