# full config options are documented at
# https://github.com/martinvonz/jj/blob/main/docs/config.md

[user]
email = "dustypomerleau@users.noreply.github.com"
name = "Dusty Pomerleau"

# available options are listed at
# https://github.com/martinvonz/jj/blob/main/cli/src/config/colors.toml
[colors]
commit_id = "bright white"
email = "bright black"
empty = "red"
"empty description placeholder" = "green"
"git_head" = "cyan"
"git_refs" = "cyan"
"op_log current_operation id" = "yellow"
"op_log current_operation time" = "bright white"
"op_log current_operation user" = "bright black"
"op_log id" = "magenta"
"op_log time" = "blue"
"op_log user" = "bright black"
"remote_branches" = "green"
"tags" = "cyan"
timestamp = "bright black"
"working_copy change_id" = "cyan"
"working_copy commit_id" = "bright white"
"working_copy description placeholder" = "bright green"
"working_copy email" = "yellow"
"working_copy empty" = "red"
"working_copy timestamp" = "blue"

[diff]
format = "git"

[template-aliases]
"format_short_id(id)" = "id.shortest()"

[ui]
editor = "nvim"
merge-editor = "vscode"
pager = "delta"
