# A full list of formatting options is available at
# https://github.com/tamasfe/taplo/blob/master/site/site/configuration/formatter-options.md
# with additional configuration options in neighboring files

[formatting]
align_comments = false
allowed_blank_lines = 1
column_width = 100
reorder_keys = true
