-- you could do something like:
-- local function map(mode, keys, exec, opts)
--     vim.keymap.set(mode, keys, exec, opts or { silent = true, noremap = true })
-- end

local key = vim.api.nvim_set_keymap

key("n", "<c-h>", "<c-w><c-h>", { noremap = true, })
key("n", "<c-j>", "<c-w><c-j>", { noremap = true, })
key("n", "<c-k>", "<c-w><c-k>", { noremap = true, })
key("n", "<c-l>", "<c-w><c-l>", { noremap = true, })
key("n", "<c-w>h", "<c-w>H", { noremap = true, })
key("n", "<c-w>j", "<c-w>J", { noremap = true, })
key("n", "<c-w>k", "<c-w>K", { noremap = true, })
key("n", "<c-w>l", "<c-w>L", { noremap = true, })
key("n", "<leader>c", "<cmd>noh<cr>", { noremap = true, })
key("n", "<leader>o", "<cmd>so $MYVIMRC<cr>", { noremap = true, })
key("n", "<leader>s", "<cmd>w<cr>", { noremap = true, })
key("n", "<leader>w", "<cmd>q<cr>", { noremap = true, })
key("n", "<leader>W", "<cmd>qa<cr>", { noremap = true, })
key("n", "<leader>x", "<cmd>bd<cr>", { noremap = true, })
key("n", "<localleader>f", ":Neoformat prettier<cr>", { noremap = true, })
key("n", "<localleader>i", "<cmd>Inspect<cr>", { noremap = true, })
key("n", "<localleader>l", ":LspInfo<cr>", { noremap = true, })
key("n", "<localleader>p", "<cmd>pwd<cr>", { noremap = true, })
key("n", "<localleader>u", ":Lazy update<cr>", { noremap = true, })
key("n", "\\", ",", { noremap = true, })
key("n", "∆", ":<c-u> m+<cr>==", { noremap = true, silent = true, })
key("n", "˚", ":<c-u> m-2<cr>==", { noremap = true, silent = true, })
key("x", "∆", ":<c-u> '<,'>move'>+<cr>gv=gv", { noremap = true, silent = true, })
key("x", "˚", ":<c-u> '<,'>m-2<cr>gv=gv", { noremap = true, silent = true, })
