return {
    {
        "lewis6991/gitsigns.nvim",
        event = "VeryLazy",
        config = true,
        keys = {
            {
                "<leader><leader>g",
                "<cmd>Gitsigns toggle_signs<cr>",
                mode = { "n", },
                noremap = true,
            },
            {
                "<localleader>gb",
                "<cmd>Gitsigns stage_buffer<cr>",
                mode = { "n", },
                noremap = true,
            },
            {
                "<localleader>gc",
                "<cmd>Gitsigns change_base<cr>",
                mode = { "n", },
                noremap = true,
            },
            {
                "<localleader>gd",
                "<cmd>Gitsigns diffthis<cr>",
                mode = { "n", },
                noremap = true,
            },
            {
                "<localleader>gh",
                "<cmd>Gitsigns stage_hunk<cr>",
                mode = { "n", },
                noremap = true,
            },
            {
                "<localleader>gm",
                "<cmd>Gitsigns toggle_current_line_blame<cr>",
                mode = { "n", },
                noremap = true,
            },
            {
                "<localleader>gn",
                "<cmd>Gitsigns next_hunk<cr>",
                mode = { "n", },
                noremap = true,
            },
            {
                "<localleader>gN",
                "<cmd>Gitsigns prev_hunk<cr>",
                mode = { "n", },
                noremap = true,
            },
            {
                "<localleader>gp",
                "<cmd>Gitsigns preview_hunk<cr>",
                mode = { "n", },
                noremap = true,
            },
            {
                "<localleader>grb",
                "<cmd>Gitsigns reset_buffer<cr>",
                mode = { "n", },
                noremap = true,
            },
            {
                "<localleader>grc",
                "<cmd>Gitsigns reset_base<cr>",
                mode = { "n", },
                noremap = true,
            },
            {
                "<localleader>grh",
                "<cmd>Gitsigns reset_hunk<cr>",
                mode = { "n", },
                noremap = true,
            },
            {
                "<localleader>gu",
                "<cmd>Gitsigns undo_stage_hunk<cr>",
                mode = { "n", },
                noremap = true,
            },
            {
                "<localleader>gv",
                "<cmd>Gitsigns select_hunk<cr>",
                mode = { "n", },
                noremap = true,
            },
            {
                "<localleader>gw",
                "<cmd>Gitsigns toggle_word_diff<cr>",
                mode = { "n", },
                noremap = true,
            },
            {
                "<localleader>gx",
                "<cmd>Gitsigns toggle_deleted<cr>",
                mode = { "n", },
                noremap = true,
            },
            {
                "ih",
                "<cmd>Gitsigns select_hunk<cr>",
                mode = { "o", "x", },
                noremap = true,
            },
        },
    },
}
