unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# don't confirm when killing panes
bind-key x kill-pane

set -g default-terminal "screen-256color"
set -g mode-keys vi
set -g mouse on
set -g status-keys vi
set -g status-right "%A %Y–%m–%d %H:%M"
set -sg terminal-overrides ",*:RGB"
set-option -g allow-rename off # don't rename windows automatically
set-option -g focus-events on
set-option -g message-command-style "bg=#242837, fg=#ffaabb"
set-option -g message-style "bg=#242837, fg=#99ddff"
set-option -g status-style "bg=#292d3e, fg=#cac0a9"
set-option -ga terminal-features ",alacritty:usstyle"
set-option -sg escape-time 10
set-window-option -g window-status-current-style "fg=#ffaabb"

